import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./NavBar";
import { Suspense } from "react";
import { AuthProvider } from "./auth/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="synthwave" lang="en">
      <body>
        <AuthProvider>
          <NavBar />
          <main>
            <Suspense fallback={<p>Loading...</p>}>{children}</Suspense>
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
