import type { Metadata } from "next";
import { Suspense } from "react";

import NavBar from "./NavBar";
import { AuthProvider } from "./auth/Provider";
import GoogleAnalyticsScript from "./GoogleAnalyticsScript";

import "./globals.css";
import { Inter, Roboto } from "next/font/google";
// import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "...",
    description: "...",
  },
};

const inter = Inter({
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "200", "400"],
});

// const poppins = localFont({
//   src: "../public/fonts"
// })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="synthwave" lang="en">
      <GoogleAnalyticsScript />
      <body className={roboto.className}>
        <AuthProvider>
          <NavBar />
          <main className={inter.className}>
            <Suspense fallback={<p>Loading...</p>}>{children}</Suspense>
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
